# Generated by Django 4.1.6 on 2023-06-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='Год')),
                ('week', models.SmallIntegerField(verbose_name='Неделя')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'расписания',
            },
        ),
        migrations.CreateModel(
            name='ScheduleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Период расписания')),
                ('image', models.ImageField(upload_to='', verbose_name='Заполненный шаблон расписания')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='schedule.schedule')),
            ],
            options={
                'verbose_name': 'картика расписания',
                'verbose_name_plural': 'картинки расписания',
            },
        ),
    ]
